-- CreateTable
CREATE TABLE `accounts` (
    `ID_ACCOUNTS` INTEGER NOT NULL AUTO_INCREMENT,
    `ID_PERSON` INTEGER NOT NULL,
    `EMAIL` VARCHAR(50) NOT NULL,
    `PASSWORD_ACCOUNT` VARCHAR(100) NOT NULL,
    `STATE` CHAR(1) NOT NULL,

    INDEX `AC_FK_ID`(`ID_PERSON`),
    PRIMARY KEY (`ID_ACCOUNTS`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `brands` (
    `ID_BRAND` INTEGER NOT NULL,
    `NAME_BRAND` VARCHAR(50) NOT NULL,

    UNIQUE INDEX `BR_UQ_NO`(`NAME_BRAND`),
    PRIMARY KEY (`ID_BRAND`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `clinic_histories` (
    `ID_CLINIC_HISTORY` INTEGER NOT NULL,
    `NAME_PATIENT` VARCHAR(50) NOT NULL,

    PRIMARY KEY (`ID_CLINIC_HISTORY`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `dependencies` (
    `ID_DEPARTMENT` INTEGER NOT NULL AUTO_INCREMENT,
    `DEPARTMENT_NAME` VARCHAR(50) NOT NULL,
    `TYPE_DEPARTMENT` CHAR(1) NOT NULL,

    UNIQUE INDEX `DE_UQ_DE`(`DEPARTMENT_NAME`),
    PRIMARY KEY (`ID_DEPARTMENT`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `feature_products` (
    `ID_FEATURE` INTEGER NOT NULL AUTO_INCREMENT,
    `EXPIRATION_DATE` DATE NOT NULL,
    `QUANTITY_PER_UNIT` INTEGER NOT NULL,
    `PRICE_PER_UNIT` INTEGER NOT NULL,
    `INVIMA` VARCHAR(50) NOT NULL,
    `MANUFACTURING_DATE` DATE NULL,

    PRIMARY KEY (`ID_FEATURE`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `history_item` (
    `ID_ITEM` INTEGER NOT NULL,
    `ID_DEPARTMENT` INTEGER NOT NULL,
    `DATE_HISTORY_ITEM` TIMESTAMP(0) NULL DEFAULT CURRENT_TIMESTAMP(0),
    `QUANTITY` INTEGER NOT NULL,
    `ID_USER` INTEGER NOT NULL,

    INDEX `HI_FK_DE`(`ID_DEPARTMENT`),
    PRIMARY KEY (`ID_ITEM`, `ID_DEPARTMENT`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `history_user` (
    `ID_HISTORY` INTEGER NOT NULL AUTO_INCREMENT,
    `DATE_CREATE` TIMESTAMP(0) NULL DEFAULT CURRENT_TIMESTAMP(0),
    `ID_PERSON` INTEGER NOT NULL,

    PRIMARY KEY (`ID_HISTORY`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `item` (
    `ID_ITEM` INTEGER NOT NULL AUTO_INCREMENT,
    `PRESENTATION` CHAR(1) NOT NULL,
    `QUANTITY` INTEGER NOT NULL,
    `ID_PRODUCT` INTEGER NOT NULL,
    `ID_FEATURE` INTEGER NOT NULL,
    `ID_DEPARTMENT` INTEGER NOT NULL,

    INDEX `IT_FK_DE`(`ID_DEPARTMENT`),
    INDEX `IT_FK_FE`(`ID_FEATURE`),
    INDEX `IT_FK_PR`(`ID_PRODUCT`),
    PRIMARY KEY (`ID_ITEM`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `persons` (
    `ID_PERSON` INTEGER NOT NULL AUTO_INCREMENT,
    `FULL_NAME` VARCHAR(50) NOT NULL,
    `DOCUMENT_TYPE` CHAR(1) NOT NULL,
    `DOCUMENT` INTEGER NOT NULL,
    `GENDER` CHAR(1) NOT NULL,
    `STATE` CHAR(1) NOT NULL,
    `PROFESSIONAL_ID` INTEGER NULL,
    `ID_DEPARTMENT` INTEGER NOT NULL,

    INDEX `ID_DEPARTMENT`(`ID_DEPARTMENT`),
    PRIMARY KEY (`ID_PERSON`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `product_tracings` (
    `ID_PERSON` INTEGER NOT NULL,
    `ID_ITEM` INTEGER NOT NULL,
    `ID_CLINIC_HISTORY` INTEGER NULL,
    `QUANTITY_USED` INTEGER NOT NULL,
    `UNIT_MEASUREMENT` CHAR(1) NOT NULL,
    `DESTINY_SERVICE` CHAR(1) NOT NULL,

    INDEX `PT_FK_CH`(`ID_CLINIC_HISTORY`),
    INDEX `PT_FK_IT`(`ID_ITEM`),
    PRIMARY KEY (`ID_PERSON`, `ID_ITEM`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `products` (
    `ID_PRODUCT` INTEGER NOT NULL,
    `ID_BRAND` INTEGER NOT NULL,
    `PRODUCT_NAME` VARCHAR(50) NOT NULL,
    `MEASUREMENT_UNITS` CHAR(1) NOT NULL,
    `TYPE_PRODUCT` CHAR(1) NOT NULL,

    UNIQUE INDEX `PR_UQ_PN`(`PRODUCT_NAME`),
    INDEX `PR_FK_BR`(`ID_BRAND`),
    PRIMARY KEY (`ID_PRODUCT`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `roles` (
    `ID_ROL` INTEGER NOT NULL AUTO_INCREMENT,
    `NAME_ROL` VARCHAR(50) NOT NULL,
    `DESCRIPTION_ROL` VARCHAR(1024) NOT NULL,
    `STATE_ROL` CHAR(1) NOT NULL,

    PRIMARY KEY (`ID_ROL`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `user_roles` (
    `ID_ROL` INTEGER NOT NULL,
    `ID_PERSON` INTEGER NOT NULL,
    `STATE` CHAR(1) NOT NULL,

    INDEX `US_FK_PE`(`ID_PERSON`),
    PRIMARY KEY (`ID_ROL`, `ID_PERSON`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
